spring:
  datasource:
    url: jdbc:h2:file:./data/ecommerce
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: mysupersecretkeythatismorethan32charslong123
  expiration: 3600000

server:
  port: 8080
